### ISSUE TITLE
Implementation of T5-3b

### ISSUE THREAD

**Issue by JL5173** [ServiceNow/picard#78]
Dear author,

May I ask whether you use DeepSpeed to implement your picard on T5-3B since it reports "RuntimeError: CUDA out of memory. Tried to allocate 46.00 MiB (GPU 0; 39.59 GiB total capacity; 37.66 GiB already allocated; 45.19 MiB free; 37.70 GiB reserved in total by PyTorch)" when I try to implement your codings with t5-3b? Thanks

**Comment by tscholak** [comment]
Hi @JL5173, I used a single A100 without DeepSpeed. Can you please reduce the device batch size to 1? If this still doesn't work, try activating gradient checkpointing.

**Comment by JL5173** [comment]
Thanks, that's very helpful, yes, when meeting a big PLM, we have to reduce batch size. One more question, may I know the size of nums_beam that you set during your experiment since I also think num_beams matters according to your papers? But your config just set num_beams as 1. Thanks

**Comment by tscholak** [comment]
During training I set num_beams to 1. That way, evaluation is slightly faster, and selection of best models works just as well. For evaluation, I set num_beams to 4.
