### ISSUE TITLE
Installation guide for windows

### ISSUE THREAD

**Issue by b4zyuvaraj** [ServiceNow/picard#88]
Hi

I am new to machine learning, I want to try your tool.

Is there any documents with step by step installation guide for windows?

Thanks in advance!!!

**Comment by tscholak** [comment]
Hi @b4zyuvaraj!
Thanks for checking out PICARD. There are no dedicated instructions for users of windows. At a minimum, you will need Docker and a Unix tool called make. I am not using Windows myself, so the path may be rocky. Someone else tried this already though and had at least partial success. Try a search in the closed issues. Good luck!

**Comment by b4zyuvaraj** [comment]
Hi @tscholak 

Thank you so much for the response !!!

I did followed the steps it almost worked for me. Right now I am facing the below mentioned issue,

![image](https://user-images.githubusercontent.com/100585096/163945902-6a9a5bd8-6369-4ff3-92ef-2ab1996ae8b3.png)

Is it mandatory to have a Nvidia GPU to run?

**Note: I am using Windows 10**
