### ISSUE TITLE
How to deploy PICARD model in AKS

### ISSUE THREAD

**Issue by hithisiskathirvel** [ServiceNow/picard#90]
Hi Team,

Have a great day!!

I have successfully installed and running PICARD model in ML Azure Notebooks.

I want this PICARD model to deploy into an Azure kubernetes services.

 Can you please help me to find out the solution.

**Comment by tscholak** [comment]
Hi @hithisiskathirvel!
If you know how to deploy docker containers that expose REST services, then you will also be able to deploy our model.
Best,
Torsten

**Comment by hithisiskathirvel** [comment]
Hi @tscholak  I have try to push the tscholak/text-to-sql-eval image into my container registry. But it takes long time.Still didn't pushed in container registry. can u plz help me. 
TIA
