### ISSUE TITLE
Adapting to SPARQL

### ISSUE THREAD

**Issue by kotalaraghava** [ServiceNow/picard#91]
Hey @tscholak ,

Hope you are doing good!

I am looking at ways to adapt for other SQL engines (SPARQL, Mysql, Postgresetc..). I was looking at the code [here](https://github.com/ElementAI/picard/tree/main/picard/src/Language/SQL) parser written for spider SQL, you are marking a call to this using Facebook thrift.

I am wondering what is the way to adapt it for above mentioned SQL engine, does it get easy for some engineers like Mysql as the current one is SQLite belongs somewhat similar compared to SPARQL.

can we use already built [syntax ](pypi.org/project/sqlvalidator/) validators instead of writing one? with compromising accuracy? 

Thanks for the help as always!

**Comment by tscholak** [comment]
Hi @kotalaraghava,
The thrift library is used for communication between the parser and the beam search algorithm. The parser is written in Haskell, and the beam search is using the hf transformers, a Python package.
New SQL engines can be supported by adding a parser for each one of them. These parser would need to be written in Haskell as well. The existing SQLite parser is of limited use for that. Note also that it has been written to work best on Spider's subset of SQLite, and doesn't even support the whole SQLite spec.
