### ISSUE TITLE
Initial setup error(s) 

### ISSUE THREAD

**Issue by navaneetham-aicomputing** [ServiceNow/picard#93]
@tscholak and team, thanks a lot for let PICARD available for public. I am sure this help many NLP researchers life easy. I did many experiments with PICARD(HF environment) works awesome. I try to explore PICARD in two of my local environments: 

Environments Configurations:
1. MAC M1 chip (aware there are issues with few python packages)
2. GCP E2-Standard "Linux box with 32GB RAM & 8vCPU"). 
3. Python 3.9 was installed on both machines. 

Followed below steps as per instructions given in README and issue(#36) 
```
- git clone git@github.com:ElementAI/picard.git
- cd picard
- git submodule update --init --recursive
- poetry shell
- poetry install 
```

installation throw below error on both environments: 

```
  **ValueError**
  picard is not a package.
```
**Note**: Please find the screenshot below

I did notice others also reported similar issue #36 . As per @tscholak recommendation I did "`poetry install --no-root`"
No errors. But when I try to run `python seq2seq/run_seq2seq.py` getting below error. Any idea what needs to be done to resolve this issue? 

```
(py) ➜  picard git:(main) ✗ python seq2seq/run_seq2seq.py
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
Traceback (most recent call last):
  File "seq2seq/run_seq2seq.py", line 20, in <module>
    from transformers.models.auto import AutoConfig, AutoTokenizer, AutoModelForSeq2SeqLM
ImportError: cannot import name 'AutoModelForSeq2SeqLM' from 'transformers.models.auto' (/Users/nav/opt/anaconda3/envs/py37/lib/python3.7/site-packages/transformers/models/auto/__init__.py)
```
 
Looks like I am missing something? I am happy to provide more information if needed. 

![Screenshot 2022-05-18 at 09 52 32](https://user-images.githubusercontent.com/67477877/169004956-fb36eafe-1355-495c-a0c3-4f51ff57ff8b.png)

**Comment by tscholak** [comment]
Hi, the code in this repository is not compatible with non-x86 architectures, unfortunately.

**Comment by iMayK** [comment]
Hi, the error is also there for x86.

**Comment by sbajpai2** [comment]
Even I am facing the similar issue.
Is this resolved?


![Screen Shot 2022-11-09 at 5 23 18 PM](https://user-images.githubusercontent.com/8160392/200970443-ee5b5d03-8136-49fe-8143-03261db9f066.png)
