### ISSUE TITLE
Question about Details of PICARD's SQL Parsing Rules

### ISSUE THREAD

**Issue by ryangawei** [ServiceNow/picard#94]
Hi @tscholak,

Thank you and your team for the excellent work.

I have a few questions regarding the rules in PICARD's parsing.
1) In lexing mode, have you used any SQL parser to detect spelling errors and reject invalid column names? Or is it solely based on some string matching rules?
2) During beam search there could be statements that look like the following
```
select id from
select count(name
select population from city where district =
```
In parsing w/o and w/ guard mode, I believe these statements should pass the check since it's "partially correct" and can be completed in the next beam search. However they should be rejected by the regular SQL syntax as they're not "fully correct". While implementing PICARD's SQL syntax, how do you deal with such condition?

Thanks!

**Comment by tscholak** [comment]
Hi @ryangawei,

1. Yes, spelling errors in SQL keywords and invalid column names are rejected in lexing mode.
2. Expressions that can be continued to correct SQL are admitted by the parser. PICARD is an incremental parser, and code is only rejected if it is already incorrect and cannot be made correct by continuing it.
