### ISSUE TITLE
PICARD for Cross-lingual Parsing

### ISSUE THREAD

**Issue by tomsherborne** [ServiceNow/picard#97]
Hi @tscholak !

Thanks for the really great codebase for PICARD. I'm looking at how PICARD style decoding could help with a parser for multiple languages. I think I might need to re-train the base parser using mT5 instead of English T5. Did you try this? 

I am assuming the process would be the same but replaces the pre-trained model in the config if this is for CSPIDER (same SQL, different input utterances). I'm happy to work on a PR to add Cspider as a dataset if I find that this works well. Let me know if this would be valuable.

**Comment by tscholak** [comment]
Hi @tomsherborne!
I haven't tried mT5 or CSpider with this codebase. I think thought that this would be a cool thing to try. Contributions are very welcome!
